### ISSUE TITLE
Question about Testnet Native Segwit Addresses

### ISSUE THREAD

**Issue by arianDGI** [nimiq/php-xpub#5]
Is there any reason why testnet Native Segwit addresses derived from a vpub start with "tc1.." instead of "tb1.."? If there is a reason behind it i don't mind, just wanted the explanation.

**Comment by sisou** [comment]
Good question, might be a bug. https://iancoleman.io/bip39/ for `BTC - Bitcoin Testnet` and `BIP84` (vpub) generates `tb1` addresses :/

**Comment by sisou** [comment]
Fixed in 9b52b6db932d098e35ad1238151298081ff6d0f3, released as version 1.4.1. Thanks for reporting!
